### ISSUE TITLE
method [Sync.awaitResult]  param [timeout] not work

### ISSUE THREAD

**Issue by mm0rz** [vert-x3/vertx-sync#24] opened 2017-12-28 07:36 UTC
I test the method 
```
@Suspendable
  protected void testExecSyncMethodWithNoParamsAndHandlerWithReturnNoTimeout() {
    System.out.println(System.currentTimeMillis());
    String res = awaitResult(h -> ai.methodWithNoParamsAndHandlerWithReturnTimeout(h, 1000), 2000);
    System.out.println(System.currentTimeMillis());
    assertEquals("wibble", res);
    complete();
  }

  @Suspendable
  protected void testExecSyncMethodWithNoParamsAndHandlerWithReturnTimedout() {
    System.out.println(System.currentTimeMillis());
    String res = awaitResult(h -> ai.methodWithNoParamsAndHandlerWithReturnTimeout(h, 1000), 500);
    System.out.println(System.currentTimeMillis());
    assertNull(res);
    complete();
  }
```
I revise a little bit original unit testing
the output time are

1514445905198
1514445906203

1514445910048
1514445911049

it seems like the param 'timeout' doesn't effect

**Comment by vietj** [comment] 2018-01-08 12:06
can you have a look at @jponge ?

**Comment by jponge** [comment] 2018-01-08 13:37
@vietj I will

**Comment by jponge** [comment] 2018-01-08 14:33
Both test cases with timeouts take the same time:

![screen shot 2018-01-08 at 15 28 56](https://user-images.githubusercontent.com/25961/34675089-b75811b4-f488-11e7-88dc-b2563d2cee40.png)

Interestingly in the case where a 500ms timeout is set it does take a full second to complete (so the `Thread.sleep` is awaited for) but the test is still correct as `awaitResult` did return the right thing).

**Comment by jponge** [comment] 2018-01-08 14:48
I've added a trace probe just to check and in all cases `methodWithNoParamsAndHandlerWithReturnTimeout` completes, but the result of `awaitResult` is properly impacted by the timeout.

**Comment by jponge** [comment] 2018-01-08 15:00
Confirmed:

```java
  @Suspendable
  protected void testExecSyncMethodWithNoParamsAndHandlerWithReturnNoTimeout() {
    long start = System.currentTimeMillis();
    String res = awaitResult(h -> ai.methodWithNoParamsAndHandlerWithReturnTimeout(h, 1000), 2000);
    System.out.println("[without timeout] It took " + (System.currentTimeMillis() - start) + "ms");
    assertEquals("wibble", res);
    complete();
  }

  @Suspendable
  protected void testExecSyncMethodWithNoParamsAndHandlerWithReturnTimedout() {
    long start = System.currentTimeMillis();
    String res = awaitResult(h -> ai.methodWithNoParamsAndHandlerWithReturnTimeout(h, 1000), 500);
    System.out.println("[with timeout] It took " + (System.currentTimeMillis() - start) + "ms");
    assertNull(res);
    complete();
  }
```

Traces:

```
[with timeout] It took 1008ms
[without timeout] It took 1005ms
```

**Comment by jponge** [comment] 2018-01-08 20:40
It's not a bug but the way Quasar works. It doesn't play well with `Thread.sleep`.

I'm opening a PR with reworked tests.

**Comment by jponge** [comment] 2018-04-05 12:42
Merged

**Closed as completed by jponge** 2018-04-05 12:42 UTC
Labels: enhancement

**Comment by vietj** [comment] 2018-04-05 12:50
please set 3.6.0 version on the issue

**Comment by jponge** [comment] 2018-04-05 13:45
@vietj I wanted to do it, but I don't have permissions to create milestones on this project.

**Comment by vietj** [comment] 2018-04-05 15:01
that's weird because I've seen other developers able to achieve it.

**Comment by vietj** [comment] 2018-04-05 15:08
https://github.com/vert-x3/vertx-sync/milestones you should have a button "new milestone" green

**Comment by jponge** [comment] 2018-04-05 15:55
All good now
